source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'designpattern' do
    pod 'RealmSwift'
    pod 'SVProgressHUD'
    pod 'SwiftLint'
    pod 'R.swift'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Kingfisher', '~> 4.0'
end
